NIKA/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('client/', include('PIECE.urls')),    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PIECE/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


##Cadastros######
class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('O email deve ser definido.')
        
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)

class User(AbstractBaseUser):
    nome = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    ##icon_user = models.ImageField(upload_to='imagens/icon_user/',null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nome']

    objects = UserManager()

    def __str__(self):
        return self.email
##################

#Consultas
class Minerais(models.Model):
    nome = models.CharField(max_length=100)
    icon_mineral = models.ImageField(upload_to='imagens/icon_minerais/',null=True)
    def __str__(self):
        return self.nome

class Solo(models.Model):
    nome = models.CharField(max_length=100)
    icon_solo = models.ImageField(upload_to='imagens/icon_solo/',null=True)
    def __str__(self):
        return self.nome
    
class PH(models.Model):
    nome = models.CharField(max_length=100)
    icon_PH = models.ImageField(upload_to='imagens/icon_PH/',null=True)
    def __str__(self):
        return self.nome
    
class Irrigacao(models.Model):
    nome = models.CharField(max_length=100)
    icon_irrigacao = models.ImageField(upload_to='imagens/icon_Irrigacao/',null=True)
    def __str__(self):
        return self.nome

class ExposicaoSolar(models.Model):
    nome = models.CharField(max_length=100)
    icon_exposicaosolar = models.ImageField(upload_to='imagens/icon_exposicao_solar/',null=True)
    def __str__(self):
        return self.nome

class Estacao(models.Model):
    nome = models.CharField(max_length=100)
    icon_estacao = models.ImageField(upload_to='imagens/icon_estacao/',null=True)
    def __str__(self):
        return self.nome
############################################

#cadastros//consultas#
class Especies(models.Model):
    nome = models.CharField(max_length=100)
    nome_cientifico = models.CharField(max_length=100, null=True)
    detalhes = models.CharField(max_length=260, null=True)
    necessidade_solo = models.ForeignKey(Solo, on_delete=models.CASCADE)
    acidez_solo = models.ForeignKey(PH, on_delete=models.CASCADE)
    exposicao_solar = models.ForeignKey(ExposicaoSolar, on_delete=models.CASCADE)
    estacao_producao = models.ForeignKey(Estacao, on_delete=models.CASCADE)
    irrigacao = models.ForeignKey(Irrigacao, on_delete=models.CASCADE)
    imagem_especie = models.ImageField(upload_to='imagens/especies/',null=True)
    imagem_fruta = models.ImageField(upload_to='imagens/frutas/',null=True)
    
class EspeciesMinerais(models.Model):
    especie = models.ForeignKey(Especies, on_delete=models.CASCADE)
    mineral = models.ForeignKey(Minerais, on_delete=models.CASCADE)
    quantidade = models.CharField(max_length=100, null=True)

class Plantas(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    especie = models.ForeignKey(Especies, on_delete=models.CASCADE)
    solo = models.ForeignKey(Solo, on_delete=models.CASCADE)
    exposicao_solar_atual = models.ForeignKey(ExposicaoSolar, on_delete=models.CASCADE)
    estacao_producao = models.ForeignKey(Estacao, on_delete=models.CASCADE)
    irrigacao = models.ForeignKey(Irrigacao, on_delete=models.CASCADE)
    acidez_solo = models.ForeignKey(PH, on_delete=models.CASCADE)
    dt_plantio = models.DateField()


    def __str__(self):
        return f"{self.especie.nome} - {self.usuario.username}"

class Manutencao(models.Model):
    planta = models.ForeignKey(Plantas, on_delete=models.CASCADE)
    dt_ultima_fertilizacao = models.DateField()
    ultima_medicao_ph = models.DateField()
    dt_ultima_poda = models.DateField()
    ultimo_ph = models.ForeignKey(PH, on_delete=models.CASCADE)
    solo_atual = models.ForeignKey(Solo, on_delete=models.CASCADE)
    exposicao_solar_atual = models.ForeignKey(ExposicaoSolar, on_delete=models.CASCADE)

    
    def __str__(self):
        return f"Manutencao de {self.planta}"

class Producao(models.Model):
    planta = models.ForeignKey(Plantas, on_delete=models.CASCADE)
    dt_ultima_producao = models.DateField()
    estacao_ultima_producao = models.ForeignKey(Estacao, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"Producao de {self.planta}"
##########################################
#### ocioso ###############################
class HistoricoDatas(models.Model):
    planta = models.ForeignKey(Plantas, on_delete=models.CASCADE)
    dt_ultima_fertilizacao = models.DateField(null=True, blank=True)
    ultima_medicao_ph = models.DateField(null=True, blank=True)
    dt_ultima_poda = models.DateField(null=True, blank=True)
    dt_ultima_producao = models.DateField(null=True, blank=True)
    ultimo_ph= models.ForeignKey(PH, on_delete=models.CASCADE, null=True, blank=True)
    Solo = models.ForeignKey(Solo, on_delete=models.CASCADE, null=True, blank=True)
    exposicao_solar = models.ForeignKey(ExposicaoSolar, on_delete=models.CASCADE, null=True, blank=True)
    Estacao = models.ForeignKey(Estacao, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"Histórico de Datas para {self.planta}"
############################################

PIECE/forms.py
# forms.py

from django import forms
from .models import Especies, Minerais,Estacao,Solo,PH,Irrigacao,ExposicaoSolar,EspeciesMinerais,User,Manutencao,Plantas,Producao
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('nome', 'email', 'password1', 'password2')

class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    
class EspeciesForm(forms.ModelForm):
    class Meta:
        model = Especies
        fields = (
            'nome',
            'nome_cientifico',
            'necessidade_solo',
            'acidez_solo',
            'exposicao_solar',
            'estacao_producao',
            'irrigacao',
            'imagem_especie',
            'imagem_fruta',
        )

class MineraisForm(forms.ModelForm):
    class Meta:
        model = Minerais
        fields = (
            'nome',
            'icon_mineral',
        )
class EstacaoForm(forms.ModelForm):
    class Meta:
        model = Estacao
        fields = (
            'nome',
            'icon_estacao',
        )
class PHform(forms.ModelForm):
    class Meta:
        model = PH
        fields = (
            'nome',
            'icon_PH',
        )
class soloForm(forms.ModelForm):
    class Meta:
        model = Solo
        fields = (
            'nome',
            'icon_solo',
        )
class IrrigacaoForm(forms.ModelForm):
    class Meta:
        model = Irrigacao
        fields = (
            'nome',
            'icon_irrigacao',
        )

class SolForm(forms.ModelForm):
    class Meta:
        model = ExposicaoSolar
        fields = (
            'nome',
            'icon_exposicaosolar',
        )
        
class CadastroEspecieMineralForm(forms.ModelForm):
    class Meta: 
        model = EspeciesMinerais
        fields = (
            'especie',
            'mineral',
            'quantidade',
        )
class ManutencaoForm(forms.ModelForm):
    class Meta:
        model = Manutencao
        fields = ['dt_ultima_fertilizacao', 'ultima_medicao_ph', 'dt_ultima_poda','ultimo_ph','solo_atual','exposicao_solar_atual','planta']
class ProducaoForm(forms.ModelForm):
    class Meta:
        model = Producao
        fields = ['planta', 'dt_ultima_producao','estacao_ultima_producao']    
class PlantasForm(forms.ModelForm):
    class Meta:
        model = Plantas
        fields = '__all__'
        widgets = {
            'dt_plantio': forms.DateInput(attrs={'class': 'input', 'placeholder': 'Data de Plantio'}),
            }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # obtém o usuário passado como argumento
        super().__init__(*args, **kwargs)
        if user:
            self.fields['usuario'].initial = user  # define o usuário como valor inicial do campo

templates/CadastroPlanta.html
{% extends 'base.html' %}
{% block title %}<title>Cadastrar Planta</title>{% endblock %}
{% block main %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" data-tag="font"/>
      <main class="homepage-container">
        <div class="homepage-formulariopagina">
          <div class="homepage-formulario">
            <pre>
            </pre>
            <pre>
            </pre>
            <pre>
            </pre>
            <form class="homepage-form alert alert-info " method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <input type="hidden" name="usuario" id="id_usuario" value={{ user.id }}>
              <!-- Form Name -->
              <legend>Cadastrar Planta</legend>
              
              <!-- Text input-->
              <div class="form-group row">
                  <label class="col-md-6 control-label" for="id_especie">Especie</label>
                  <label class="col-md-6 control-label" for="dt_plantio">Data de Plantio</label>

                  <label class="col-md-6">
                    <select id="id_especie" name="especie" class="form-control">
                      <option value=""></option>
                      {% for especie in especies %}
                      <option value="{{ especie.id }}">{{ especie.nome }}</option>
                      {% endfor %}
                    </select>        </label>          
                
                    <label class="col-md-6">
                      <input id="id_dt_plantio" type ='date' name="dt_plantio" class="form-control">
                    </input></label>
                    </div>
              
                    <pre>  </pre>
              <div class="form-group row">
                <label class="col-md-6 control-label" for="id_acidez_solo">Acidez do solo</label>
                <div class="col-md-6">
                  <select id="id_acidez_solo" name="acidez_solo" class="form-control">
                    <option value=""></option>
                    {% for PH in phs %}
                    <option value="{{ PH.id }}">{{ PH.nome }}</option>
                    {% endfor %}
                  </select>
                </div>
              
                <pre> </pre>
              <!-- Select Basic -->
              
                <label class="col-md-6 control-label" for="id_solo">Tipo de Solo</label>
                <div class="col-md-6">
                  <select id="id_solo" name="solo" class="form-control">
                    <option value=""></option>
                    {% for Solo in solos %}
                    <option value="{{ Solo.id }}">{{ Solo.nome }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <pre> </pre>
              
              <!-- Select Basic -->
              <div class="form-group row">
                <label class="col-md-6 control-label" for="id_estacao_producao">ultima estação de produção</label>
                <div class="col-md-6">
                  <select id="id_estacao_producao" name="estacao_producao" class="form-control">
                    <option value=""></option>
                    {% for estacao in estacoes %}
                    <option value="{{ estacao.id }}">{{ estacao.nome }}</option>
                    {% endfor %}
                  </select>
                </div>
              
                <pre> </pre>
              <!-- Select Basic -->
              
                <label class="col-md-6 control-label" for="id_exposicao_solar_atual">Exposção Solar</label>
                <div class="col-md-6">
                  <select id="id_exposicao_solar_atual" name="exposicao_solar_atual" class="form-control">
                    <option value=""></option>
                    {% for ExposicaoSolar in exposicaoSolar %}
                    <option value="{{ ExposicaoSolar.id }}">{{ ExposicaoSolar.nome }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <pre> </pre>
              <!-- Select Basic -->
              <div class="form-group row">
                <label class="col-md-6 control-label" for="id_irrigacao">Irrigação</label>
                <div class="col-md-6">
                  <select id="id_irrigacao" name="irrigacao" class="form-control">
                    <option value=""></option>
                    {% for Irrigacao in irrigacoes %}
                    <option value="{{ Irrigacao.id }}">{{ Irrigacao.nome }}</option>
                    {% endfor %}
                  </select>
                </div>
              
              
              <pre> </pre>
                <label class="col-md-4 row-md-6 control-label" for="Registrar"></label>
                <div class="col-md-4 row-md-6">
                  <button id="Registrar" name="Registrar" type="submit" class="btn btn-primary">Registrar</button>
                </div>
              </div>
              
              
            
              </form>
          </div>  
        </div>
      </main>
      {% endblock %}

templates/base_perfil_especies.html
{% extends 'base.html' %}
{% block title %}<title>{{ especie.nome }}</title>{% endblock %}
{% block main %}
      <main class="homepage-container">
        <div class="homepage-galleryplanta">
          <div class="homepage-containercentralplanta">
            <div class="homepage-containerimagemdetalhes">
              <div class="homepage-imagem">
                <div
                  class="imagemplanta-gallery-card imagemplanta-root-class-name1"
                >
                <img alt="Imagem da Espécie" src="{{ especie.imagem_especie.url }}" class="imagemplanta-image" id="imagem-especie">
                <img alt="Imagem da Fruta" src="{{ especie.imagem_fruta.url }}" class="imagemplanta-image" id="imagem-fruta" style="display: none;">
                <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                <script>
                    $(document).ready(function() {
                        $('#imagem-especie').click(function() {
                            $('#imagem-especie').hide();
                            $('#imagem-fruta').show();
                        });
                
                        $('#imagem-fruta').click(function() {
                            $('#imagem-fruta').hide();
                            $('#imagem-especie').show();
                        });
                    });
                </script>
                </div>
              </div>
              <div class="homepage-detalhes">
                <div
                  class="detalhes-testimonial-card detalhes-root-class-name3"
                >
                  <span class="detalhes-text">
                  <span>Nome: {{ especie.nome }}</span><br></br>
                  <span>Nome Cientifico: {{ especie.nome_cientifico }}</span>
                  </span>
                  <!--span class="detalhes-text2"><span>{{ especie.detalhes }}</span></span> --> 
                </div>
              </div>
            </div>
            <div class="homepage-mineraisgaleria">
              
              <div class="homepage-galleryminerais">
                
                {% for mineral in minerais %}
                <div class="mineralcard-gallery-card mineralcard-root-class-name15">
                  <img src="{{ mineral.mineral.icon_mineral.url }}" class="mineralcard-image" alt={{ mineral.mineral.nome }} title={{mineral.mineral.nome }}   />
                  <h10 class="mineralcard-text">
                    <span>{{ mineral.quantidade }}</span>
                  </h10>
                </div>
              {% endfor %}
              </div>
            </div>
          </div>
          <div class="homepage-containerplantassoloestacao">
            <div class="homepage-containersolirrigacaoestacao">
              <div class="homepage-containerestacao">
                <div
                  class="estacaoproducao-testimonial-card estacaoproducao-root-class-name8"
                >
                  <img
                    alt="{{ especie.estacao_producao.nome }}"
                    src={{ especie.estacao_producao.icon_estacao.url }}
                    class="estacaoproducao-image"
                  />
                  <div class="estacaoproducao-testimonial">
                    <span class="estacaoproducao-text"><span>{{ especie.estacao_producao }}</span></span>
                  </div>
                </div>
              </div>
              <div class="homepage-containerirrigacaosol">
                <div
                  class="irrigaosol-testimonial-card irrigaosol-root-class-name8"
                >
                  <div class="irrigaosol-testimonial">
                    <img
                      alt="profile"
                      src={{ especie.irrigacao.icon_irrigacao.url }}
                      class="irrigaosol-image"
                    />
                    <span class="irrigaosol-text"><span>{{ especie.irrigacao }}</span></span>
                  </div>
                  <div class="irrigaosol-testimonial1">
                    <img
                      alt="profile"
                      src={{ especie.exposicao_solar.icon_exposicaosolar.url }}
                      class="irrigaosol-image1"
                    />
                    <span class="irrigaosol-text1"><span>{{ especie.exposicao_solar }}</span></span>
                  </div>
                </div>
              </div>
            </div>
            <div class="solo-testimonial-card solo-root-class-name5">
              <div class="solo-testimonial">
                <img
                  alt="profile"
                  src={{ especie.acidez_solo.icon_PH.url }}
                  class="solo-image"
                />
                <span class="solo-text col-6"><span> PH - {{ especie.acidez_solo }}</span></span>
              </div>
              <div class="solo-testimonial1">
                <img
                  alt="profile"
                  src={{ especie.necessidade_solo.icon_solo.url }}
                  class="solo-image1"
                />
                <span class="solo-text1 col-6"><span>Solo - {{ especie.necessidade_solo }}</span></span>
              </div>
            </div>
          </div>
        </div>
      </main>
      {% endblock %}
    <script src="https://unpkg.com/@teleporthq/teleport-custom-scripts"></script>

templates/cadastroespecie.html
{% extends 'base.html' %}
{% block title %}<title>Cadastrar Espécie</title>{% endblock %}
{% block main %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" data-tag="font"/>
      <main class="homepage-container">
        <div class="homepage-formulariopagina">
          <div class="homepage-formulario">
            <pre>
            </pre>
            <pre>
            </pre>
            <pre>
            </pre>
            <form class="homepage-form alert alert-info " method="POST" enctype="multipart/form-data">
              {% csrf_token %}
                         
              
              <!-- Form Name -->
              <legend>Cadastrar espécie</legend>
              
              <!-- Text input-->
              <div class="form-group row">
                <div class="col-md-6">
                
                <input id="id_nome" name="nome" type="text"  placeholder="Nome Popular" class="form-control input-md" required="">
                </div>  
              
                <!-- Text input-->
               
                <div class="col-md-6">
                <input id="id_nome_cientifico" name="nome_cientifico" type="text" placeholder="Nome Cientifico" class="form-control input-md h1" required="">
               
              </div>
              </div>
              <pre></pre>
              <!-- File Button --> 
              <div class="form-group row">
                
                <div class="col-md-6">
                  <label class="col-md-6 control-label " for="FOTO_FRUTO">Foto Fruto</label>
                 
                  <input id="id_imagem_fruta" name="imagem_fruta" class="col-md-4 input-file form-control input-md" type="file">
                </div>
             
              
                
                <div class="col-md-6">
                  <label class="col-md-6 control-label " for="Imagem">Foto espécie</label>
                  
                  <input id="id_imagem_especie" name="imagem_especie" class="col-md-4 input-file form-control input-md" type="file">
                </div>
              </div>
              <pre> </pre>
              <!-- Select Basic -->
              <div class="form-group row">
                <label class="col-md-6 control-label" for="Acidez_solo">Acidez do solo</label>
                <div class="col-md-6">
                  <select id="id_acidez_solo" name="acidez_solo" class="form-control">
                    {% for PH in phs %}
                    <option value="{{ PH.id }}">{{ PH.nome }}</option>
                    {% endfor %}
                  </select>
                </div>
              
                <pre> </pre>
              <!-- Select Basic -->
              
                <label class="col-md-6 control-label" for="necessidade_solo">Tipo de Solo</label>
                <div class="col-md-6">
                  <select id="id_necessidade_solo" name="necessidade_solo" class="form-control">
                    {% for Solo in solos %}
                    <option value="{{ Solo.id }}">{{ Solo.nome }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <pre> </pre>
              
              <!-- Select Basic -->
              <div class="form-group row">
                <label class="col-md-6 control-label" for="estacao_producao">estações de produção</label>
                <div class="col-md-6">
                  <select id="id_estacao_producao" name="estacao_producao" class="form-control">
                    {% for estacao in estacoes %}
                    <option value="{{ estacao.id }}">{{ estacao.nome }}</option>
                    {% endfor %}
                  </select>
                </div>
              
                <pre> </pre>
              <!-- Select Basic -->
              
                <label class="col-md-6 control-label" for="exposicao_solar">Exposção Solar</label>
                <div class="col-md-6">
                  <select id="id_exposicao_solar" name="exposicao_solar" class="form-control">
                    {% for ExposicaoSolar in exposicaoSolar %}
                    <option value="{{ ExposicaoSolar.id }}">{{ ExposicaoSolar.nome }}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <pre> </pre>
              <!-- Select Basic -->
              <div class="form-group row">
                <label class="col-md-6 control-label" for="irrigacao">Irrigação</label>
                <div class="col-md-6">
                  <select id="id_irrigacao" name="irrigacao" class="form-control">
                    {% for Irrigacao in irrigacoes %}
                    <option value="{{ Irrigacao.id }}">{{ Irrigacao.nome }}</option>
                    {% endfor %}
                  </select>
                </div>
              
              
              <pre> </pre>
                <label class="col-md-4 row-md-6 control-label" for="Registrar"></label>
                <div class="col-md-4 row-md-6">
                  <button id="Registrar" name="Registrar" type="submit" class="btn btn-primary">Registrar</button>
                </div>
              </div>
              
              
            
              </form>
          </div>  
        </div>
      </main>
      {% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %}<title>homepage</title>{% endblock %}
{% block main %}
  <main class="homepage-container">
        <div class="homepage-inicio">
          <div class="homepage-plantas">
            {% for especie in especies %}
            <a href="{% url 'perfil_especie' pk=especie.id %}">
            <div
              class="plantas-card-gallery-card plantas-card-root-class-name1"
            >
              <img
                alt={{ especie.nome }}
                src={{ especie.imagem_especie.url }}
                class="plantas-card-image"
              />
              <h2 class="plantas-card-text"><span>{{ especie.nome }}</span></h2>
              <span class="plantas-card-text1">
                <span>{{ especie.nome_cientifico }}</span>
              </span>
            </div>
            {% endfor %}
            
          </div>
        </div>
      </main>{% endblock %}
  <script src="https://unpkg.com/@teleporthq/teleport-custom-scripts"></script>
  </body>
</html>

templates/login.html
{% extends 'base.html' %}
{% block title %}<title>Login</title>{% endblock %}
{% block main %}
<main class="homepage-container">
  <div class="homepage-formulariopagina">
    <div class="homepage-formulario">
      <pre>
      </pre>
      <pre>
      </pre>
      <pre>
      </pre>
      <form class="homepage-form alert alert-info " method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        
        <!-- Form Name -->
        <legend>Login</legend>
        
        <!-- Text input-->
        <div class="form-group row">
          <div class="col-md-40">
          
          <input id="id_email" name="email" type="text"  placeholder="email" class="form-control input-md" required="">
          </div>  
    
        </div>
        <pre></pre>
        <div class="form-group row">
          <div class="col-md-40">
            <input id="id_password" name="password" type="password" placeholder="password" class="form-control input-md h1" required="">      
            </div>
        </div>
        <pre></pre>

        
        
        <pre> </pre>
          <label class="col-md-4 row-md-6 control-label" for="login"></label>
          <div class="col-md-4 row-md-6">
            <button id="Login" name="login" type="submit" class="btn btn-primary">login</button>
          </div>
        </div>
        
        
      
        </form>
    </div>  
  </div>
</main>{% endblock %}
</html>

templates/register.html
{% extends 'base.html' %}
{% block title %}<title>Cadastro</title>{% endblock %}
{% block main %}
<main class="homepage-container">
  <div class="homepage-formulariopagina">
    <div class="homepage-formulario">
      <pre>
      </pre>
      <pre>
      </pre>
      <pre>
      </pre>
      <form class="homepage-form alert alert-info " method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <!-- Form Name -->
        <legend>Cadastrar</legend>
        
        <!-- Text input-->
        <div class="form-group row">
          <div class="col-md-6">
          
          <input id="id_nome" name="nome" type="text"  placeholder="Nome" maxlength="255" required="" class="form-control input-md" required="">
        </div>  
        
          <!-- Text input-->
         
          <div class="col-md-6">
          <input id="id_email" name="email" type="text" placeholder="Email" class="form-control input-md h1" required="">      
          </div>
        </div>
        <pre></pre>
        <div class="form-group row">
          <div class="col-md-6">
          
          <input id="id_password1" name="password1" type="password"  placeholder="password" class="form-control input-md" required="">
          </div>  
        
          <!-- Text input-->
         
          <div class="col-md-6">
          <input id="id_password2" name="password2" type="password" placeholder="password" class="form-control input-md h1" required="">      
          </div>
          <ul><li>Sua senha não pode ser muito parecida com o resto das suas informações pessoais.</li><li>Sua senha precisa conter pelo menos 8 caracteres.</li><li>Sua senha não pode ser uma senha comumente utilizada.</li><li>Sua senha não pode ser inteiramente numérica.</li></ul>
        </div>
        <pre></pre>

        <!-- File Button --> 
        <div class="form-group row">
          
          <div class="col-md-10">    
            
              <label class="col-md-6 control-label" for="Registrar"></label>
              
                <button type="submit" class="btn btn-primary">Registrar</button>
       
          </div>
          
          
        </div>
        
        
        <pre> </pre>
        
        
        
        
      
        </form>
    </div>  
  </div>
</main>{% endblock %}
</html>